### ISSUE TITLE
Make sure Crash-Stats buildid links continue to work

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/buildhub2#241]
For example, [a crash like this](https://crash-stats.mozilla.com/report/index/a4c34505-b9c3-49ea-a679-f21d80180823) links to https://mozilla-services.github.io/buildhub/?q=20180807170231 which is going to have to change in Crash-Stats but it should still make sure the right buildid search works and highlights.

**Comment by willkg** [comment]
Bug 1559004 covers that work. https://bugzilla.mozilla.org/show_bug.cgi?id=1559004

**Comment by willkg** [comment]
This is all set.
