### ISSUE TITLE
Help pushlog-addon migrate

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/buildhub2#351]
[This link](https://github.com/mozilla/pushlog-addon/blob/master/content.js#L110) ([permlink](https://github.com/mozilla/pushlog-addon/blob/95d946ec3d7fa824bf074ef0b0b5ece86d3b2804/content.js#L110)) might rot but it looks like this:

```javascript
async function getBuildInfo(buildid) {
  const url = "https://buildhub.prod.mozaws.net/v1/buckets/build-hub/collections/releases/search";
const query = {
   ...

```

**Comment by willkg** [comment]
I added an issue here: https://github.com/mozilla/pushlog-addon/issues/7

**Comment by willkg** [comment]
This is all set.
