### ISSUE TITLE
Help crash-stop-addon migrate

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/buildhub2#352]
See https://github.com/mozilla/crash-stop-addon/blob/a83d0440cad85caed481ffaa23559f71f57deb33/crashstop/buildhub.py#L13

**Comment by willkg** [comment]
This is tracked in the crash-stop-addon issue tracker here: https://github.com/mozilla/crash-stop-addon/issues/13

**Comment by willkg** [comment]
This is all set.
