### ISSUE TITLE
Help PollBot migrate

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/buildhub2#361]
https://github.com/mozilla/PollBot/blob/1c9748ebadd130efea398b79ebef8c7142359305/pollbot/tasks/buildhub.py#L11 and https://github.com/mozilla/PollBot/blob/1c9748ebadd130efea398b79ebef8c7142359305/pollbot/tasks/buildhub.py#L71 amongst some.

**Comment by willkg** [comment]
I wrote up an issue in the PollBot issue tracker here: https://github.com/mozilla/PollBot/issues/244

**Comment by willkg** [comment]
This is all set.
