### ISSUE TITLE
move to mozilla/services

### ISSUE THREAD

**Issue by willkg** [mozilla-services/buildhub2#530]
Buildhub and all the other things I maintain are in the mozilla-services/ github org. This project should be, too.

**Comment by willkg** [comment]
@autrilla I can make the changes in this repository. I think we have to change something in circleci. What other changes are needed to move this from one github org to another?

**Comment by autrilla** [comment]
I'm guessing I'll have to re-add all env vars to the project on CircleCI. Other than that, I don't think there's anything else that needs to be done.

**Comment by willkg** [comment]
I would like to do this, but it's not super urgent. When's a good time for you? Maybe some time in the next couple of weeks?

**Comment by autrilla** [comment]
It's a pretty low effort change, so whenever you want, really.

**Comment by willkg** [comment]
If it's really not a problem, I'd love to do it this week. Maybe tomorrow (Thursday)?

**Comment by autrilla** [comment]
Works for me! If you want, you can move the repo over today and I'll set up CircleCI again tomorrow morning my time

**Comment by willkg** [comment]
That works super! I've moved it to mozilla-services/buildhub2. I think I got the collaborators/teams thing right. I'll go through the code next and do a PR with url and github updates.

**Comment by autrilla** [comment]
The env vars seem to have migrated automagically, so I think there's no action needed on my side

**Comment by willkg** [comment]
I landed some changes and want to test out a stage and prod deploy. I'll do that monday morning my time.

If that works, then I think we're good. I can't think of anything else that would be affected.

**Comment by willkg** [comment]
I did a deploy to stage and that went fine. I think we're good here.
